version: '3'

services:
  postgres:
    image: postgres:11.5-alpine
    environment:
      POSTGRES_DB: financial_api_db
      POSTGRES_USER: financial_api_user
      POSTGRES_PASSWORD: 3x4mpl3P455w0rd
    ports:
      - "5432:5432"
